### PR TITLE
Vault support + protobuf tuning

### LINKED ISSUE #122: Add system error build status
a bug was found that took down the server over the course of an `ocelot build`. the bug was fixed, but in the aftermath the postgres database has a bunch of 'builds' that are all under `queued`.  

there should be a `error occurred` type of status that only happens on the handle of an exception in the build process. something should save to the database that this build is borked

### LINKED ISSUE #181: Names of types in creds.proto are wildly inconsistent
creds.proto needs a makeover.

The containers that hold VCS, Repo, Apple, and Kubernetes credentials are helpfully named
- `VCSCredsWrapper`
- `RepoCredsWrapper`
- `AppleCredsWrapper`
- `K8SCredsWrapper`

but the containers that hold SSH keys and Notification credentials are called
- `SSHWrap`
- `NotifyWrap`

Internal fields are all over the place too. The field inside of VCSCredWrapper is called `vcs`, but in AppleCredsWrapper it's called `appleCreds`, in K8SCredsWrapper it's called `K8SCreds` and in NotifyWrap it's just called `creds`.

This makes it very difficult to refactor and add features using existing credential types. We need to fix these such that they're consistent on both naming and case.

### LINKED ISSUE #235: orb cli - tab complete doesn't work deeper in subcommand tree
Specifically, it currently doesn't work within `orb dev` and `orb ops` because we have a positional argument (`action`) that structopt isn't handling. That was a bad shortcut to avoid the structopt boilerplate.

### PR DESCRIPTION
**Pull request by tjtelan**
High-level:
- Workflow for private repos, where you must add private key first. No more handwaving with hardcoded paths
- All client-side calls wired to a server call, and `async`
- new `Code` service, split out of the `Org` service
- Removed polling repo interfaces. We want this to be default behavior, and maybe this will simplify things?
- Adding Vault to vagrant environment, docker-compose
- Adding Vault support to Secret Service
- Standardize on verbs for CRUD ops: `add`, `get`, `update`, `remove`, `list`
- Service to service calls, with `Build` service calling `Code` and `Secret` services
- Internal API: `agent_runtime` so workflows can be shared between client and service
- standardizing on `default_org` until database support added
- A whole lot of `From<T>` conversions between error types or manual serialization/de-serialization

Perhaps this doesn't need to be stated at this stage, but I'm not yet paying attention to the backwards compatibility of the protos. I'm almost certain that we're going to do some more tuning for the database support.

Fixes #122 - I added a system error state
Closes #181 - I did spend a lot of time standardizing the Secrets interfaces so they fit in well with Vault and the future DB, specifically for LIST workflows, which was the original intention of the issue.
Fixes #235 - Rerouted cli subcommands for `developer` and `operator` tree to use more "native" structopt. Fixed the completion command to use the `SubcommandContext` struct, so tab complete actually works now.

### CODE REVIEW

File: cli/orb/src/subcommand/secret/add.rs [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+
+#[derive(Debug, StructOpt, Clone)]
+#[structopt(rename_all = "kebab_case")]
+pub struct ActionOption {
+    /// Secret name
+    #[structopt(required = true)]
+    secret_name: String,
+
+    /// Secret Type
+    #[structopt(long, required = true, possible_values = &[
```
Comment (eccramer) [inline cli/orb/src/subcommand/secret/add.rs]: I won't block on this, but we need to think about AT LEAST enforcing that these match the protobuf representation of this, and OPTIMALLY these should be either auto-generated, or parsed, from the protobuf.

File: cli/orb/src/subcommand/summary.rs [hunk 2]
```diff
@@ -12,10 +17,27 @@ pub struct SubcommandOption {
     path: Option<String>,
```
Comment (eccramer) [inline cli/orb/src/subcommand/summary.rs]: Update to PathBuf to match other code elsewhere

File: lib/git_meta/git_info.rs [hunk 3]
```diff
@@ -200,3 +202,57 @@ pub fn get_target_commit<'repo>(
         }
     }
 }
+
```
Comment (eccramer) [inline lib/git_meta/git_info.rs]: YOU WROTE TESTS ❤️ 😄

File: lib/git_meta/tests/current_commit.rs [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+    // We want to use the HEAD commit
+    let commit = None;
+
+    // We're just gonna match the shell output. Wrap with Raw quotes, and raw newline
+    let lib_current_commit = format!(
+        "\"{}\\n\"",
+        git_info::get_git_info_from_path(&current_dir_abs_path, &branch, &commit)?.id
+    );
+
+    assert_eq!(shell_current_commit, lib_current_commit);
```
Comment (eccramer) [inline lib/git_meta/tests/current_commit.rs]: 🌴 Totally Radical 🏄

File: models/orbital_headers/src/orbital_types.rs [hunk 5]
```diff
@@ -0,0 +1,265 @@
+tonic::include_proto!("orbital_types");
```
Comment (eccramer) [inline models/orbital_headers/src/orbital_types.rs]: We need to find a way to not have to hand write this.

File: services/build_service.rs [hunk 6]
```diff
@@ -1,44 +1,306 @@
...
+
+        debug!("Pulling container: {:?}", config.image.clone());
+        match build_engine::docker_container_pull(config.image.as_str()) {
+            Ok(ok) => ok, // The successful result doesn't matter
+            Err(e) => return Err(OrbitalServiceError::new(&e.to_string()).into()),
+        };
+
+        // TODO: Inject the dynamic build env vars here
+        let envs_vec = agent_runtime::parse_envs_input(&None);
+        let vols_vec = agent_runtime::parse_volumes_input(&None);
```
Comment (eccramer) [inline services/build_service.rs]: put a comment here mentioning that this vector by default (even if you pass &None) will contain the docker volume and the temp code checkout dir.

File: services/code_service.rs [hunk 7]
```diff
@@ -0,0 +1,244 @@
...
+                creds
+            }
+            SecretType::SshKey => {
+                debug!("Private repo with ssh key");
+
+                // Write private key into a temp file
+                debug!("Writing incoming ssh key to temp file");
+                let mut file = File::create(temp_keypath.as_path())?;
+                let mut _contents = String::new();
+                let _ = file.write_all(unwrapped_request.auth_data.as_bytes());
```
Comment (eccramer) [inline services/code_service.rs]: We should chat about the security implications of writing a secret like this to a temp file.

File: services/code_service.rs [hunk 8]
```diff
@@ -0,0 +1,244 @@
...
+        // let git_repo = db_get_repo(org, git_provider, git_repo_name)-> GitRepoEntry
+
+        let mut git_repo = GitRepoEntry::default();
+        git_repo.org = unwrapped_request.org;
+        git_repo.user = "git".into();
+        git_repo.git_provider = unwrapped_request.git_provider;
+        git_repo.name = unwrapped_request.name;
+        git_repo.secret_type = SecretType::SshKey.into();
+        git_repo.uri = unwrapped_request.uri;
+        git_repo.auth_data =
```
Comment (eccramer) [inline services/code_service.rs]: We should not hardcode this in the future.
